### ISSUE TITLE
hahahaha

### ISSUE THREAD

**Issue by poeticninja** [poeticninja/testy#1]

**Comment by poeticninja** [comment]
oh snap!

**Comment by developit** [comment]
are you writing a scrum plugin for github

**Comment by poeticninja** [comment]
haha, I thought about it... but instead I am testing out a couple that are really awesome. I can share my experiences if you want?

**Comment by developit** [comment]
Would be interesting in that. Sounds like a Medium post ;)

**Comment by poeticninja** [comment]
When I am done with my research I might just have to do that. 😉

**Comment by poeticninja** [comment]
@developit I am going to go ahead and close this issue. https://medium.com/@poeticninja/github-is-not-good-enough-but-so-close-54d32a702884
